name: agentic-hackathon
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - google-generativeai
      - python-dotenv         
      - streamlit
      - requests
